#pragma once

#ifdef AUDIO_ENABLE

#define STARTUP_SONG SONG(PLANCK_SOUND)
#define DEFAULT_LAYER_SONGS \
  { SONG(QWERTY_SOUND), SONG(COLEMAK_SOUND) }

#endif

#define ENCODER_RESOLUTION 4

#define ORYX_CONFIGURATOR
#define PLANCK_EZ_LED_LOWER 2
#define PLANCK_EZ_LED_RAISE 3
#define PLANCK_EZ_LED_ADJUST 4
